apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  nfs:
    path: /tmp/share1
    server: 192.168.55.240
  claimRef:
    name: webapp-pvc
    namespace: webapp

