apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 1234
      targetPort: 1234
      nodePort: 31234 

