apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapp
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 1234
        volumeMounts:
        - name: nfs-volume
          mountPath: /usr/share/nginx/html
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: webapp-pvc
      - name: config-volume
        configMap:
          name: nginx-config

